# Copyright 2026 Canonical Ltd.
# SPDX-License-Identifier: GPL-3.0-only

"""StabilizerReport - Final summary report and detailed REPORT.md."""

from pathlib import Path

from rich.console import Console
from rich.table import Table

from stabilizer.types import StabilizerState



def run(state: StabilizerState) -> StabilizerState:
    """Generate clean console summary and detailed REPORT.md with all exclusions."""
    console = Console()
    output_dir = state.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / "REPORT.md"

    console.print("\n" + "=" * 60)
    console.print(f"[bold]Stabilizer Report: {state.package}[/bold]")
    console.print(
        f"Target: {state.target_release} ({state.target_version.version if state.target_version else 'N/A'})"
    )
    console.print(
        f"Source: {state.source_release} ({state.source_version.version if state.source_version else 'N/A'})"
    )
    console.print("=" * 60)

    # Console: High-level summary only
    console.print("\n[bold]Summary:[/bold]")
    console.print(f"  Total commits analyzed: {len(state.all_commits)}")
    console.print(f"  Applicable changes: {len(state.applicable_changes)}")
    console.print(f"  Safe SRU changes: {len(state.safe_changes)}")
    console.print(f"  Testable changes: {len([tc for tc in state.testable_changes if tc.testable])}")
    console.print(f"  SRU bug templates generated: {len(state.sru_bugs)}")

    if state.exclusions:
        by_stage = {}
        for exc in state.exclusions:
            by_stage.setdefault(exc.stage, []).append(exc)

        console.print("\n[bold yellow]Exclusions by stage:[/bold yellow]")
        for stage, exclusions in by_stage.items():
            console.print(
                f"  {stage.replace('_', ' ').title()}: {len(exclusions)} excluded"
            )
        console.print(f"\n[dim]Full details including all exclusion reasons written to:[/dim]")
        console.print(f"[bold]{report_path}[/bold]")

    console.print(f"\n[bold]Output directory:[/bold] {output_dir}")

    # Generate detailed REPORT.md
    _write_detailed_report(state, report_path)

    return state


def _write_detailed_report(state: StabilizerState, report_path: Path) -> None:
    """Write comprehensive REPORT.md with all exclusions and details."""
    report = [
        f"# Stabilizer Report: {state.package}",
        "",
        f"**Target:** {state.target_release} ({state.target_version.version if state.target_version else 'N/A'})",
        f"**Source:** {state.source_release} ({state.source_version.version if state.source_version else 'N/A'})",
        "",
        "## Summary",
        f"- Total commits analyzed: {len(state.all_commits)}",
        f"- Applicable changes: {len(state.applicable_changes)}",
        f"- Safe SRU changes: {len(state.safe_changes)}",
        f"- Testable changes: {len([tc for tc in state.testable_changes if getattr(tc, 'testable', True)])}",
        f"- SRU bug templates generated: {len(state.sru_bugs)}",
        "",
    ]

    # SRU Bugs
    if state.sru_bugs:
        report.extend([
            "## Generated SRU Bug Templates",
            "",
        ])
        for bug in state.sru_bugs:
            report.extend([
                f"### {bug.title}",
                f"**File:** `{bug.filename}`",
                f"**Impact:** {bug.impact}",
                f"**Test Plan:** {bug.test_plan}",
                f"**Regression Potential:** {getattr(bug, 'regression_potential', 'N/A')}",
                "",
                "Commits:",
            ])
            for commit in bug.commits:
                report.append(f"- {commit.short_sha}: {commit.subject}")
            report.append("\n---\n")

    # Detailed Exclusions
    if state.exclusions:
        report.extend([
            "## All Exclusions",
            "",
            "Full list of every change that was evaluated but excluded, with exact reasons.",
            "",
        ])

        by_stage = {}
        for exc in state.exclusions:
            by_stage.setdefault(exc.stage, []).append(exc)

        for stage, exclusions in by_stage.items():
            stage_title = stage.replace('_', ' ').title()
            report.extend([
                f"### {stage_title} Exclusions ({len(exclusions)})",
                "",
                "| Change | Reason |",
                "|--------|--------|",
            ])
            for exc in exclusions:
                title = exc.change_title.replace("|", "\\|")
                reason = exc.reason.replace("|", "\\|").replace("\n", " ")
                report.append(f"| {title} | {reason} |")
            report.append("\n")

    report.extend([
        "",
        "---",
        f"Generated by Stabilizer on {state.output_dir}",
        "",
        "Note: SRU requires changes to be **safe**, **applicable**, and **testable**. ",
        "Only changes passing all filters generate SRU bug templates.",
    ])

    report_path.write_text("\n".join(report))
